advert_site:
    resource: "@AdvertSiteBundle/Resources/config/routing.yml"
    prefix:   /%locale%

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /%locale%

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
